"""
Tutor Dashboard — Auto-Updating Student Engagement Monitor
----------------------------------------------------------
Visualizes engagement logs generated by realtime_monitor.py
Run with:
    streamlit run src/dashboard.py
"""

import streamlit as st
import pandas as pd
import plotly.express as px
import os
import time
import threading
from datetime import timedelta

# ---------- Page Setup ----------
st.set_page_config(page_title="Student Engagement Dashboard", layout="wide")
st.title("🎓 Student Engagement Dashboard")

BASE_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
LOGS_DIR = os.path.join(BASE_DIR, "logs")
REFRESH_INTERVAL = 2  # seconds (faster refresh for live tracking)


def stop_app(message):
    """Stop cleanly in Streamlit and in bare python/debug runs."""
    st.warning(message)
    raise SystemExit(0)

# ---------- Initialize Session State ----------
if "last_update" not in st.session_state:
    st.session_state.last_update = time.time()
if "last_file" not in st.session_state:
    st.session_state.last_file = None
if "refresh_trigger" not in st.session_state:
    st.session_state.refresh_trigger = 0
if "last_seen_trigger" not in st.session_state:
    # Track the last observed trigger value from the main thread so we can
    # immediately rerun when the background monitor increments
    st.session_state.last_seen_trigger = st.session_state.refresh_trigger

# ---------- Background File Monitor ----------
def monitor_logs_directory():
    """Monitor logs directory for file changes and trigger rerun."""
    while True:
        try:
            if os.path.exists(LOGS_DIR):
                csv_files = [f for f in os.listdir(LOGS_DIR) if f.endswith(".csv")]
                if csv_files:
                    # Get most recently modified file
                    latest_file = max(
                        csv_files,
                        key=lambda f: os.path.getmtime(os.path.join(LOGS_DIR, f))
                    )
                    # If file changed, trigger refresh
                    if (st.session_state.last_file != latest_file or 
                        time.time() - st.session_state.last_update > REFRESH_INTERVAL):
                        st.session_state.last_file = latest_file
                        st.session_state.last_update = time.time()
                        st.session_state.refresh_trigger += 1
        except Exception:
            pass
        time.sleep(REFRESH_INTERVAL)

# Start background monitor thread (daemon, runs only once per session)
monitor_thread = threading.Thread(target=monitor_logs_directory, daemon=True)
if not hasattr(st.session_state, "monitor_started"):
    monitor_thread.start()
    st.session_state.monitor_started = True

# ---------- Auto Refresh with Polling ----------

# Use Streamlit's autorefresh if available, plus manual polling via session state
try:
    st.autorefresh(interval=REFRESH_INTERVAL * 1000, limit=None, key="refresh")
    autorefresh_ok = True
except Exception:
    autorefresh_ok = False

# Show refresh status
if autorefresh_ok:
    st.info("✅ Auto-refresh is enabled. Running session monitored continuously.")
else:
    st.info("⚠️ Auto-refresh not available — using background polling to track running session.")

# If the background monitor updated `refresh_trigger`, force an immediate
# rerun from the main thread so the UI updates promptly in this session.
# This complements `st.autorefresh` and ensures environments without it still
# get near-instant updates.
try:
    if st.session_state.refresh_trigger != st.session_state.last_seen_trigger:
        st.session_state.last_seen_trigger = st.session_state.refresh_trigger
        # Trigger a Streamlit rerun from the main thread
        st.experimental_rerun()
except Exception:
    # If experimental_rerun isn't available for some reason, fall back to
    # the periodic autorefresh/polling already in place.
    pass

# ---------- Load Latest Session ----------
os.makedirs(LOGS_DIR, exist_ok=True)
csv_files = sorted([f for f in os.listdir(LOGS_DIR) if f.endswith(".csv")], reverse=True)

if not csv_files:
    stop_app("No session logs found. Run realtime_monitor.py first.")

# Option to follow the latest running session (the one realtime_monitor.py is
# currently writing). When enabled we auto-select the newest CSV.
follow_latest = st.checkbox("Follow latest running session (auto-select)", value=True)
# Always get the most recently modified file when following latest
if follow_latest:
    files_with_mtime = []
    for f in csv_files:
        file_path = os.path.join(LOGS_DIR, f)
        if os.path.isfile(file_path):
            files_with_mtime.append((f, os.path.getmtime(file_path)))

    if not files_with_mtime:
        stop_app("No readable session logs found right now. Please try again in a moment.")

    selected_file = max(files_with_mtime, key=lambda x: x[1])[0]
    st.write(f"📍 Following: **{selected_file}** | Refresh count: {st.session_state.refresh_trigger}")
else:
    selected_file = st.selectbox("Select a session:", csv_files, index=0)

path = os.path.join(LOGS_DIR, selected_file)

# Load session data fresh on each run (no caching for live data)
def load_session_data(file_path):
    """Load session CSV. Fetches fresh data on each Streamlit rerun."""
    try:
        data = pd.read_csv(file_path)
        return data
    except Exception as e:
        st.error(f"Error loading file: {e}")
        return None

# Use refresh_trigger to force reload on background monitor updates
_ = st.session_state.refresh_trigger  # Reference to trigger rerun
df = load_session_data(path)

if df.empty or "label" not in df.columns:
    stop_app("Selected log file has no valid data.")

# ---------- Manual Refresh Button ----------
col1, col2 = st.columns([3, 1])
with col2:
    if st.button("🔄 Refresh Now", use_container_width=True):
        st.session_state.refresh_trigger += 1
        st.rerun()

# ---------- Summary ----------
st.markdown("### 📊 Engagement Summary")
summary = df["label"].value_counts(normalize=True) * 100

col1, col2, col3, col4 = st.columns(4)
col1.metric("Attentive", f"{summary.get('Attentive', 0):.1f}%")
col2.metric("Confused", f"{summary.get('Confused', 0):.1f}%")
col3.metric("Distracted", f"{summary.get('Distracted', 0):.1f}%")
col4.metric("Sleeping", f"{summary.get('Sleeping', 0):.1f}%")

st.divider()

# ---------- Charts ----------
fig_pie = px.pie(
    df, names="label", title="Engagement Breakdown",
    color_discrete_map={"Attentive": "green", "Confused": "gold", "Distracted": "red", "Sleeping": "royalblue"}
)
st.plotly_chart(fig_pie, use_container_width=True)

st.divider()

df["timestamp"] = pd.to_datetime(df["timestamp"], format="%H:%M:%S", errors="coerce")
if df["timestamp"].isna().all():
    # Fallback: build a synthetic timeline so the line chart still renders.
    start = pd.Timestamp.now().floor("s")
    df["timestamp"] = [start + timedelta(seconds=i) for i in range(len(df))]
else:
    df["timestamp"] = df["timestamp"].fillna(method="ffill")
    if df["timestamp"].isna().any():
        first_valid = df["timestamp"].dropna()
        if not first_valid.empty:
            df["timestamp"] = df["timestamp"].fillna(first_valid.iloc[0])
        else:
            start = pd.Timestamp.now().floor("s")
            df["timestamp"] = [start + timedelta(seconds=i) for i in range(len(df))]

timeline = df.groupby(["timestamp", "label"], dropna=False).size().reset_index(name="count")

fig_line = px.line(
    timeline, x="timestamp", y="count", color="label",
    title="Engagement Over Time",
    color_discrete_map={"Attentive": "green", "Confused": "gold", "Distracted": "red", "Sleeping": "royalblue"},
    markers=True
)
if timeline.empty:
    st.warning("Timeline data is empty for the selected session.")
else:
    st.plotly_chart(fig_line, use_container_width=True)

# ---------- Data Table ----------
with st.expander("📄 View Raw Data"):
    st.dataframe(df.tail(50), use_container_width=True)

st.success("✅ Dashboard running smoothly!")


